### ISSUE TITLE
Repeating sequential word should not be allowed "agile agile"

### ISSUE THREAD

**Issue by pereij33** [BrunnerLivio/agile-ipsum#16]
## Current behavior
Some sentences don't make sense since they are repeated one after another : example scrum scrum.

## Expected behavior
Words should be random and yet not repeating one after another.

## Possible Solution
Ban duplicates.

**Comment by BrunnerLivio** [comment]
As you can see [here](https://github.com/BrunnerLivio/agile-ipsum/blob/b9e87b948030952e81e8b2eaf72ea69b9b56f954/src/pages/index.js#L15-L20), agile-ipsum is making use of the library called [lorem-ipsum](https://www.npmjs.com/package/lorem-ipsum). Lorem Ipsum does not take these duplicates into account. Therefore I suggest you either

- contribute directly to [lorem ipsum](https://github.com/knicklabs/lorem-ipsum.js)
- or check in this repository for duplicate words. You could do that by evaluating the generated string in [src/pages/index.js](https://github.com/BrunnerLivio/agile-ipsum/blob/master/src/pages/index.js).

**Comment by BrunnerLivio** [comment]
Fixed with #21
