### ISSUE TITLE
Website not responding anymore when number of paragraphs too big

### ISSUE THREAD

**Issue by sn00zey** [BrunnerLivio/agile-ipsum#17]
## Current behavior
When entering a too big number in the paragraph field, then the website stops responding.

## Expected behavior
Website is responding all the time, even if a big nr. of paragraphs are entered.

## Possible Solution
Limitation of paragraphs in order to prevent the website from not responding anymore.

**Comment by BrunnerLivio** [comment]
Let's limit it to 50. 
Feel free to open a pull request yourself! :)

**Comment by BrunnerLivio** [comment]
Fixed with #22 and 72d7738
